-- SQL Setup for Shelter Sync (GraphQL Version)
-- Run this in the Supabase SQL Editor to ensure your database matches the script's expectations.

-- 1. Create the table if it doesn't exist
create table if not exists public.sheltersv2 (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Core BBR Data
    bygning_id uuid not null unique, -- The "id_lokalId" from BBR
    shelter_capacity integer,        -- "byg069Sikringsrumpladser"
    anvendelse text,                 -- "byg021BygningensAnvendelse"
    kommunekode text,                -- "kommunekode"
    
    -- Address Data (from DAR)
    address text,                    -- Full address string
    vejnavn text,
    husnummer text,
    postnummer text,
    location geometry(Point, 4326),  -- GeoJSON location
    
    -- System Metadata
    last_checked timestamp with time zone,
    deleted timestamp with time zone -- If set, the shelter is considered "soft deleted"
);

-- 2. Create indexes for performance
create index if not exists idx_sheltersv2_bygning_id on public.sheltersv2 (bygning_id);
create index if not exists idx_sheltersv2_deleted on public.sheltersv2 (deleted);

-- 3. Create Sync State table (for resuming progress)
create table if not exists public.sync_state (
    id int primary key default 1,
    cursor text,
    last_run timestamp with time zone default now(),
    constraint single_row check (id = 1) -- Ensure only one row
);

-- Insert initial row if not exists
insert into public.sync_state (id, cursor, last_run)
values (1, null, now())
on conflict (id) do nothing;

-- 4. Enable Row Level Security (RLS) - Optional but recommended
alter table public.sheltersv2 enable row level security;
alter table public.sync_state enable row level security;

-- 5. Create policies
create policy "Enable read access for all users" on public.sheltersv2 for select using (true);
create policy "Enable full access for service role" on public.sheltersv2 for all using (true) with check (true);
create policy "Enable full access for service role state" on public.sync_state for all using (true) with check (true);