name: Weekly Progress Monitor

on:
  schedule:
    # Run every Sunday at 10:00 UTC for weekly progress report
    - cron: '0 10 * * 0'
  workflow_dispatch:

jobs:
  progress-report:
    name: Weekly Progress Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3 python-dotenv

      - name: Generate Weekly Progress Report
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "=== WEEKLY PROGRESS REPORT ==="
          echo "Date: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Run ID: ${{ github.run_id }}"
          echo ""
          python monitor_global_progress.py

      - name: Comment on Issue (if triggered manually)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v6
        with:
          script: |
            const report = `## Weekly Progress Report
            
            **Date:** ${new Date().toISOString().split('T')[0]}
            **Repository:** ${context.repo.owner}/${context.repo.repo}
            **Run ID:** ${context.runId}
            
            Progress report generated successfully. Check the workflow logs for detailed information.
            
            ---
            *Generated by GitHub Actions*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            }); 